### ISSUE TITLE
TypeError: Cannot read property 'theme' of undefined after first start

### ISSUE THREAD

**Issue by tbsvttr** [ixartz/Next-js-Blog-Boilerplate#5]
`git clone --depth=1 https://github.com/ixartz/Next-js-Blog-Boilerplate.git website-next-js`
`cd website-next-js/`
`yarn`
`yarn run dev`

results in:

`yarn run v1.22.10
$ next
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
error - ./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[2].oneOf[6].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[2].oneOf[6].use[2]!./src/styles/main.css
TypeError: Cannot read property 'theme' of undefined`

**Comment by ixartz** [comment]
Hi @tbsvttr,

The project currently doesn't support yarn.

Please run the following command: git clone https://github.com/ixartz/Next-js-Blog-Boilerplate.git website-next-js
cd website-next-js/
npm install
npm run dev

I'm currently working to add the yarn support.
