### ISSUE TITLE
Doesn't work with Yarn and Next.js 12.0.7

### ISSUE THREAD

**Issue by kkomelin** [ixartz/Next-js-Blog-Boilerplate#6]
After cloning the project, I ran:

```
yarn
yarn dev
```

When loaded the app page in Chrome, the console output:

```
error - ./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[2].oneOf[6].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[2].oneOf[6].use[2]!./src/styles/main.css
TypeError: Cannot read property 'theme' of undefined
```

**Comment by kkomelin** [comment]
It's a duplicate actually https://github.com/ixartz/Next-js-Blog-Boilerplate/issues/5

Please add the information about incompatibility with Yarn into the README file.

**Comment by ixartz** [comment]
Hi @kkomelin,

Yes, please use npm instead for the current time being.

**Comment by kkomelin** [comment]
Hi @ixartz,
Thanks for your reply.

I've just upgraded Next to 12.0.7 and started receiving the same issue. 
Any ideas on how to fix it?

**Comment by ixartz** [comment]
Hi @kkomelin,

I think there is some incompatible dependency when your update package json to the latest version.

**Comment by ixartz** [comment]
For the time being, you might need to keep the package-lock. If I'm not wrong if they're not some much new feature in SSG mode.

I'm planning to totally rewrite this project and add several new features. It was my first open source project and I made some mistakes.

If you need the latest version Next JS 12, I have another project:
https://github.com/ixartz/Next-js-Boilerplate
And add the blog feature from this project.

**Comment by kkomelin** [comment]
Thanks @ixartz
