### ISSUE TITLE
Update the publish directory for netlify.toml

### ISSUE THREAD

**Issue by maxcell** [ixartz/Next-js-Blog-Boilerplate#8]
Howdy there!

Looks like you're using Next v12. With Next on Netlify, we need to modify where we're setting the output directory too. I think you can actually remove it from there all together and default to using `.next`. See here for the source https://github.com/netlify/netlify-plugin-nextjs

So far it looks like if you use the Deploy to Netlify Button to deploy the project, it will fail:

<details><summary>Deploy Log</summary>

```
9:35:26 AM: ────────────────────────────────────────────────────────────────
9:35:26 AM:   Plugin "@netlify/plugin-nextjs" failed                        
9:35:26 AM: ────────────────────────────────────────────────────────────────
9:35:26 AM: ​
9:35:26 AM:   Error message
9:35:26 AM:   Error: The directory "out" does not contain a Next.js production build. Perhaps the build command was not run, or you specified the wrong publish directory.
9:35:26 AM:   Your publish directory is set to "out", but in most cases it should be ".next".
9:35:26 AM:   If you are using "next export" then you should set the environment variable NETLIFY_NEXT_PLUGIN_SKIP to "true".
9:35:26 AM: ​
9:35:26 AM:   Plugin details
9:35:26 AM:   Package:        @netlify/plugin-nextjs
9:35:26 AM:   Version:        4.2.4
9:35:26 AM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
9:35:26 AM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
9:35:26 AM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
```

</details>

If you're open to it, I think this should be a small fix but could even help out the Next-js-Boilerplate project too. I can try to open a PR for it today!

**Comment by ixartz** [comment]
Hi @maxcell, thank you for letting me know and sharing the issue. It seems netlify enable the nextjs plugin by default but in this project, we only use `next export`.

So, we should disable this plugin for this export and also for Next-js-Boilerplate too.

Here is some documentation I have found:
https://github.com/netlify/netlify-plugin-nextjs#use-with-next-export
https://github.com/netlify/netlify-plugin-nextjs/blob/main/demos/next-export/netlify.toml#L7

It might help to solve the issue.

I'm totally open to it, let me know when you have the fix.

**Comment by ixartz** [comment]
Hi @maxcell, thank you for reporting the issue. I have just solve the issue by adding this line: https://github.com/ixartz/Next-js-Blog-Boilerplate/blob/master/netlify.toml#L6

It should now fixed the issue and works as expected.

Sorry to commit the solution myself, someone reported the same issue and I wanted to solve quickly.

Let me know if the problem persists.

**Comment by maxcell** [comment]
No worries at all! Thank you for creating such a valuable resource for people getting themselves started!
